"""add Users Chats DB models

Revision ID: 2567130ec210
Revises: 3b853ad76675
Create Date: 2023-12-19 03:47:54.496464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2567130ec210'
down_revision: Union[str, None] = '3b853ad76675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.CheckConstraint("type in ('private', 'conversation')", name='ck_type_of_user_conversation'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index(op.f('ix_chats_peer_id'), 'chats', ['peer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_peer_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
