"""add Users Chats DB models

Revision ID: 9ee185e2fe31
Revises: 2567130ec210
Create Date: 2023-12-19 03:57:58.286111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee185e2fe31'
down_revision: Union[str, None] = '2567130ec210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###
