"""add Users Chats DB models

Revision ID: b59a83decb24
Revises: 9ee185e2fe31
Create Date: 2023-12-19 04:13:36.672307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59a83decb24'
down_revision: Union[str, None] = '9ee185e2fe31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_chats_user_id_users'), 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chats_user_id_users'), 'chats', type_='foreignkey')
    # ### end Alembic commands ###
